# This credentials secret allows cloudflared to authenticate itself
# to the Cloudflare infrastructure.
{{- if not .Values.cloudflare.existingSecretCred }}
{{- if .Values.cloudflare.tunnelCli }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cloudflare-tunnel.fullname" . }}-creds
  labels:
    {{- include "cloudflare-tunnel.labels" . | nindent 4 }}
stringData:
  credentials.json: |-
    {
      "AccountTag":   {{ .Values.cloudflare.tunnelCli.account    | default "" | quote }},
      "TunnelID":     {{ .Values.cloudflare.tunnelCli.tunnelId   | default "" | quote }},
      "TunnelName":   {{ .Values.cloudflare.tunnelCli.tunnelName | default "" | quote }},
      "TunnelSecret": {{ .Values.cloudflare.tunnelCli.secret     | default "" | quote }}
    }
{{- end }}
{{- end }}
