# This credentials secret allows cloudflared to authenticate itself
# to the Cloudflare infrastructure.
apiVersion: v1
kind: Secret
metadata:
{{- if .Values.cloudflare.existingSecretCred }}
  # this is an example of the secret that needs to be created, but w/o the "--sample" suffix
  name: {{ include "cloudflare-tunnel.fullname" . }}-creds--sample
  labels:
    {{- include "cloudflare-tunnel.labels" . | nindent 4 }}
stringData:
  credentials.json: |-
    {
      "AccountTag":   "00000000-0000-0000-0000-000000000000",
      "TunnelID":     "00000000-0000-0000-0000-000000000000",
      "TunnelName":   "example-tunnel-name",
      "TunnelSecret": "xxxxxxxxxxxx"
    }
{{- else }}
  name: {{ include "cloudflare-tunnel.fullname" . }}-creds
  labels:
    {{- include "cloudflare-tunnel.labels" . | nindent 4 }}
stringData:
  {{- if .Values.cloudflare.tunnelCli }}
  credentials.json: |-
    {
      "AccountTag":   {{ .Values.cloudflare.tunnelCli.account    | default "" | quote }},
      "TunnelID":     {{ .Values.cloudflare.tunnelCli.tunnelId   | default "" | quote }},
      "TunnelName":   {{ .Values.cloudflare.tunnelCli.tunnelName | default "" | quote }},
      "TunnelSecret": {{ .Values.cloudflare.tunnelCli.secret     | default "" | quote }}
    }
  {{- else }}
  {}
  {{- end }}
{{- end }}
