# This credentials secret allows cloudflared to authenticate itself
# to the Cloudflare infrastructure.
{{- if not .Values.cloudflare.existingSecret }}
{{- if .Values.cloudflare.tunnelToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cloudflare-tunnel.fullname" . }}
  labels:
    {{- include "cloudflare-tunnel.labels" . | nindent 4 }}
stringData:
  TUNNEL_TOKEN: {{ .Values.cloudflare.tunnelToken }}
{{- end }}
{{- end }}
